# Generated by Django 5.2 on 2025-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKey",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlatformConfiguration",
        ),
        migrations.DeleteModel(
            name="SystemSetting",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AddField(
            model_name="role",
            name="email",
            field=models.EmailField(
                default="johndoe@gmail.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="last_name",
            field=models.CharField(default="Doe", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="phone_number",
            field=models.CharField(default=256772772772, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="role_name",
            field=models.CharField(default="Administrator", max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
