# Generated by Django 5.2 on 2025-05-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company_profile", models.TextField()),
                ("geo_logs", models.TextField()),
                ("vehicle_or_rider", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CourierPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on_time_percentage", models.FloatField()),
                ("rating", models.FloatField()),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courier.courier",
                    ),
                ),
            ],
        ),
    ]
