# Generated by Django 5.2 on 2025-05-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("condition", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("refund_option", models.CharField(max_length=50)),
                ("pickup_scheduled", models.BooleanField(default=False)),
                ("return_warehouse_location", models.CharField(max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        ),
    ]
