# Generated by Django 5.2 on 2025-05-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courier", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("route_details", models.TextField()),
                ("eta", models.DateTimeField()),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("reattempt_date", models.DateTimeField(blank=True, null=True)),
                ("customer_rating", models.FloatField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courier.courier",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        ),
    ]
